//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventStack.ExtentReports.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GherkinLangs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GherkinLangs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AventStack.ExtentReports.Resources.GherkinLangs", typeof(GherkinLangs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;af&quot;: {
        ///    &quot;and&quot;: [
        ///      &quot;* &quot;,
        ///      &quot;En &quot;
        ///    ],
        ///    &quot;background&quot;: [
        ///      &quot;Agtergrond&quot;
        ///    ],
        ///    &quot;but&quot;: [
        ///      &quot;* &quot;,
        ///      &quot;Maar &quot;
        ///    ],
        ///    &quot;examples&quot;: [
        ///      &quot;Voorbeelde&quot;
        ///    ],
        ///    &quot;feature&quot;: [
        ///      &quot;Funksie&quot;,
        ///      &quot;Besigheid Behoefte&quot;,
        ///      &quot;Vermoë&quot;
        ///    ],
        ///    &quot;given&quot;: [
        ///      &quot;* &quot;,
        ///      &quot;Gegewe &quot;
        ///    ],
        ///    &quot;name&quot;: &quot;Afrikaans&quot;,
        ///    &quot;native&quot;: &quot;Afrikaans&quot;,
        ///    &quot;scenario&quot;: [
        ///      &quot;Situasie&quot;
        ///    ],
        ///    &quot;scenarioOutline&quot;: [
        ///      &quot;Situasie Uiteensetting&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
    }
}
