//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventStack.ExtentReports.Reporter.Configuration.Default {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class ExtentHtmlReporterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExtentHtmlReporterSettings defaultInstance = ((ExtentHtmlReporterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExtentHtmlReporterSettings())));
        
        public static ExtentHtmlReporterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("utf-8")]
        public string encoding {
            get {
                return ((string)(this["encoding"]));
            }
            set {
                this["encoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https")]
        public string protocol {
            get {
                return ((string)(this["protocol"]));
            }
            set {
                this["protocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("standard")]
        public string theme {
            get {
                return ((string)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Extent Framework")]
        public string documentTitle {
            get {
                return ((string)(this["documentTitle"]));
            }
            set {
                this["documentTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Extent Framework")]
        public string reportName {
            get {
                return ((string)(this["reportName"]));
            }
            set {
                this["reportName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string js {
            get {
                return ((string)(this["js"]));
            }
            set {
                this["js"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string css {
            get {
                return ((string)(this["css"]));
            }
            set {
                this["css"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string enableCategoryView {
            get {
                return ((string)(this["enableCategoryView"]));
            }
            set {
                this["enableCategoryView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string enableExceptionView {
            get {
                return ((string)(this["enableExceptionView"]));
            }
            set {
                this["enableExceptionView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string enableAuthorView {
            get {
                return ((string)(this["enableAuthorView"]));
            }
            set {
                this["enableAuthorView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string enableTestRunnerLogsView {
            get {
                return ((string)(this["enableTestRunnerLogsView"]));
            }
            set {
                this["enableTestRunnerLogsView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string enableTimeline {
            get {
                return ((string)(this["enableTimeline"]));
            }
            set {
                this["enableTimeline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string chartVisibleOnOpen {
            get {
                return ((string)(this["chartVisibleOnOpen"]));
            }
            set {
                this["chartVisibleOnOpen"] = value;
            }
        }
    }
}
